// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentalCar_System.Models.Entity;

public partial class CarAddress
{
    public Guid AddressId { get; set; }

    public Guid? CarId { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Ward { get; set; }

    public string Street { get; set; }

    public virtual Car Car { get; set; }
}