// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentalCar_System.Models.Entity;

public partial class Image
{
    public Guid ImgId { get; set; }

    public Guid? CarId { get; set; }

    public byte[] Photo { get; set; }

    public virtual Car Car { get; set; }
}